# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns the inverse matrix using Rcpp Armadillo
#'
#' @export
invC <- function(M) {
    .Call(`_heavyRpackage_invC`, M)
}

#'@rdname mvnpdf
#'@export
#'
mvnpdfoptimC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_heavyRpackage_mvnpdfoptimC`, x, mean, varcovM, Log)
}

#'@rdname mvnpdf
#'@export
mvnpdfsmartC <- function(x, mean, varcovM, Log = TRUE) {
    .Call(`_heavyRpackage_mvnpdfsmartC`, x, mean, varcovM, Log)
}

#' @export
timesTwo <- function(x) {
    .Call(`_heavyRpackage_timesTwo`, x)
}

